services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./infra/postgres-init:/docker-entrypoint-initdb.d # create db for keycloak
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"

  auth-provider:
    image: quay.io/keycloak/keycloak:26.1.3
    depends_on:
      - db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - ./infra/realm-config:/opt/keycloak/data/import

  showcase:
    build:
      context: .
      dockerfile: ./showcase/Dockerfile
    depends_on:
      - db
      - cache
      - auth-provider
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/shop
      SPRING_R2DBC_USERNAME: username
      SPRING_R2DBC_PASSWORD: password
      SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/shop
      SPRING_LIQUIBASE_USER: username
      SPRING_LIQUIBASE_PASSWORD: password
      SPRING_DATA_REDIS_HOST: cache
      SPRING_DATA_REDIS_PORT: 6379
      SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI: http://auth-provider:8080/realms/shopview
      SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SHOWCASE_CLIENT_SECRET: 54neD5Uk3qNy9LDjF85cAljqhYyfTUCf # see in infra/realm-config/shopview-realm.json
      APP_IMAGES_UPLOAD_DIR: /tmp/uploads/images
      APP_PAYMENT_SERVICE_URL: http://paymentservice:8081/v1
    restart: unless-stopped
    ports:
      - "8080:8080"

  paymentservice:
    build:
      context: .
      dockerfile: ./paymentservice/Dockerfile
    depends_on:
      - db
      - auth-provider
      - showcase # because of db migrations
    environment:
      SERVER_PORT: 8081
      SPRING_R2DBC_URL: r2dbc:postgresql://db:5432/shop
      SPRING_R2DBC_USERNAME: username
      SPRING_R2DBC_PASSWORD: password
      SPRING_LIQUIBASE_URL: jdbc:postgresql://db:5432/shop
      SPRING_LIQUIBASE_USER: username
      SPRING_LIQUIBASE_PASSWORD: password
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: http://auth-provider:8080/realms/shopview
    restart: unless-stopped
    ports:
      - "8081:8081"

  db-init:
    image: postgres:17.4
    depends_on:
      - db
      - showcase
      - paymentservice
    environment:
      PGPASSWORD: password
    volumes:
      - ./infra/data.sql:/data.sql:ro
    entrypoint: >
      sh -c "until pg_isready -h db -p 5432; do echo 'Waiting for DB...'; sleep 1; done;
             echo 'Running data initialization'; psql -h db -U username -d shop -f /data.sql"
    restart: "no"
    profiles:
      - db-init

volumes:
  db-data: