services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d # create db for keycloak
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"

  auth_provider:
    image: quay.io/keycloak/keycloak:26.1.3
    depends_on:
      - db
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secret
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    restart: unless-stopped
    ports:
      - "8090:8080"
    volumes:
      - ./realm-config:/opt/keycloak/data/import

volumes:
  db-data: