services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - "8081:8080"

volumes:
  db-data: