services:
  db:
    image: postgres:17.4
    restart: always
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  cache:
    image: redis:7.4.2
    restart: always
    ports:
      - "6379:6379"

  auth_provider:
    image: quay.io/keycloak/keycloak:26.1.3
    ports:
      - "8090:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: start-dev
    restart: unless-stopped

volumes:
  db-data: