spring:
  application:
    name: shopview
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: username
    password: password
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  hikari:
    transaction-isolation: 2
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

app:
  images:
    upload-dir: uploads/images
    base-url: /images/
