spring:
  application:
    name: shopview
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: username
    password: password
  hikari:
    transaction-isolation: 2
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

      # https://stackoverflow.com/a/54774762
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
        cache:
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

app:
  images:
    upload-dir: uploads/images
    base-url: /images/
