spring:
  application:
    name: shopview
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shop
    username: username
    password: password
    pool:
      enabled: true
      initial-size: 5
      max-size: 15
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  hikari:
    transaction-isolation: 2
  liquibase:
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
#  jpa:
#    show-sql: true
#    properties:
#      # todo: ReactiveCaching (Caffeine, Redis) для реактивного приложения вместо стандартного кэширования
#      hibernate:
#        format_sql: true
#        cache:
#          use_second_level_cache: true
#          region:
#            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory

app:
  images:
    upload-dir: uploads/images
    base-url: /images/
