logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
spring:
  application:
    name: shopview
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shop
    username: username
    password: password
    pool:
      enabled: true
      initial-size: 5
      max-size: 15
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  hikari:
    transaction-isolation: 2
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
    url: jdbc:postgresql://localhost:5432/shop
    user: username
    password: password
  cache:
    type: caffeine
    cache-names: orders,products
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=30m
app:
  images:
    upload-dir: uploads/images
    base-url: /images/
  payment-service:
    url: http://localhost:8081/v1