logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
spring:
  application:
    name: shopview
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shop
    username: username
    password: password
    pool:
      enabled: true
      initial-size: 5
      max-size: 15
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  hikari:
    transaction-isolation: 2
  liquibase:
    enabled: true
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
    database-change-log-table: showcase_databasechangelog
    database-change-log-lock-table: showcase_databasechangeloglock
    url: jdbc:postgresql://localhost:5432/shop
    user: username
    password: password
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  cache:
    redis:
      time-to-live: PT1M
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8090/realms/shopview
        registration:
          showcase:
            provider: keycloak
            authorizationGrantType: client_credentials
            client-id: showcase
            client-secret: qWYwpcUChkjhg5n9umUJTaBlrzSQqB34
            scope: profile
            clientAuthenticationMethod: client_secret_post
app:
  images:
    upload-dir: uploads/images
    base-url: /images/
  payment-service:
    url: http://localhost:8081/v1
    default-balance: 300