logging:
  level:
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
server:
  port: 8081
springdoc:
  swagger-ui:
    enabled: true
spring:
  application:
    name: paymentservice
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/shop
    username: username
    password: password
    pool:
      enabled: true
      initial-size: 5
      max-size: 15
      max-idle-time: 30s
      max-life-time: 10m
      validation-query: SELECT 1
  liquibase:
    enabled: true
    contexts: "!test"
    change-log: "classpath:/db/changelog/db.changelog-master.xml"
    database-change-log-table: paymentservice_databasechangelog
    database-change-log-lock-table: paymentservice_databasechangeloglock
    url: jdbc:postgresql://localhost:5432/shop
    user: username
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/shopview