CREATE DATABASE keycloak;
CREATE USER keycloak WITH PASSWORD 'secret';
GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

\connect keycloak;
GRANT ALL PRIVILEGES ON SCHEMA public TO keycloak;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO keycloak;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO keycloak;
